# Generated by Django 5.2.7 on 2025-12-04 22:34

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(unique=True)),
                ('prompt_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('clip_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=256, null=True)),
                ('clip_score', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('final_score', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_kind', models.CharField(blank=True, max_length=100, null=True)),
                ('source_name', models.CharField(blank=True, max_length=255, null=True)),
                ('page_url', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('ctx_text', models.TextField()),
                ('ctx_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('ctx_score', models.FloatField(blank=True, null=True)),
                ('ctx_sem_score', models.FloatField(blank=True, null=True)),
                ('ctx_confidence', models.FloatField(blank=True, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='imggen.researchimage')),\
            ],
            name='WhiteboardObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('kind', models.CharField(default='vector', max_length=32)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
