# Generated by Django 5.2.7 on 2025-12-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imggen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whiteboardobject',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='whiteboardobject',
            name='data',
        ),
        migrations.AddField(
            model_name='whiteboardobject',
            name='letter_gap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whiteboardobject',
            name='letter_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whiteboardobject',
            name='pos_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='whiteboardobject',
            name='pos_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='whiteboardobject',
            name='scale',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='whiteboardobject',
            name='kind',
            field=models.CharField(choices=[('image', 'Image JSON'), ('text', 'Text prompt')], max_length=10),
        ),
    ]
